name: Rust Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --verbose --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: workspacer-${{ matrix.os }}
          path: |
            ./target/release/workspacer${{ matrix.os == 'windows-latest' && '.exe' || '' }}
